# Generated by Django 3.1 on 2022-02-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='A', max_length=150, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
