# Generated by Django 3.1 on 2022-02-25 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productWebsite', '0002_auto_20220224_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='sale_done',
            field=models.BooleanField(default=False),
        ),
    ]
