# Generated by Django 3.1 on 2022-02-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productWebsite', '0003_shoppingcart_sale_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='reference',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
