# Generated by Django 3.1 on 2022-02-25 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('productWebsite', '0005_auto_20220226_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingcart',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='shoppingcart',
            name='delivery_time',
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=20, verbose_name='PostalCode')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('street', models.CharField(max_length=100, verbose_name='Name Street')),
                ('number', models.CharField(max_length=10, verbose_name='Number')),
                ('direction_aux', models.TextField(blank=True, max_length=200, null=True, verbose_name='More info of the Direction')),
                ('delivery_date', models.DateTimeField(blank=True, null=True)),
                ('delivery_time', models.TimeField(blank=True, null=True)),
                ('shopCart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productWebsite.shoppingcart')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
