# Generated by Django 3.1 on 2022-02-25 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productWebsite', '0006_auto_20220226_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
