# Generated by Django 3.1 on 2022-02-27 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productWebsite', '0009_auto_20220227_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Delivery Date'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='delivery_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Delivery Hour'),
        ),
    ]
