# Generated by Django 3.1 on 2022-02-27 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productWebsite', '0010_auto_20220227_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='products',
            new_name='shop_cart_products',
        ),
    ]
